#pragma config(Sensor, in1,    catapultButton, sensorAnalog)
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           catapultRightA, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           catapultRightB, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           catapultLeftA, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapultLeftB, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           hookServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          liftGrab,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*--------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
float changeRange(float x, float in_min, float in_max, float out_min, float out_max)
{
	return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
void fireCatapult()
{
	motor[hookServo] = 80;
	motor[catapultLeftA] = 127;
	motor[catapultRightA] = 127;
	motor[catapultLeftB] = 127;
	motor[catapultRightB] = 127;
	wait1Msec(500);
	motor[catapultLeftA] = 0;
	motor[catapultRightA] = 0;
	motor[catapultLeftB] = 0;
	motor[catapultRightB] = 0;
}
void resetCatapult()
{
	motor[hookServo] = -30;
	motor[catapultLeftA] = 127;
	motor[catapultRightB] = 127;
	motor[catapultLeftA] = 127;
	motor[catapultRightB] = 127;
	while(SensorValue[catapultButton] <225);
	wait1Msec(500);
	motor[catapultLeftA] = 0;
	motor[catapultRightB] = 0;
	motor[catapultLeftA] = 0;
	motor[catapultRightB] = 0;
}
task robotDrive()
{
	wait1Msec(5);
	while(1)
	{
		// XDRIVE
		float x,y,z;
		x = changeRange(vexRT[Ch1],-127,127,-1,1);
		y = changeRange(vexRT[Ch2],-127,127,-1,1);
		z = changeRange(vexRT[Ch4],-127,127,-1,1);
		x = x*x;
		y = y*y;
		z = z*z;
		x = changeRange(x,-1,1,-127,127);
		y = changeRange(y,-1,1,-127,127);
		z = changeRange(z,-1,1,-127,127);
		if(vexRT[Ch1] < 0)
			x = x*-1
		if(vexRT[Ch2] < 0)
			y = y*-1
		if(vexRT[Ch4] < 0)
			z = z*-1
	writeDebugStreamLine("%d %d %d", x, y, z);
		motor[frontLeft]  =   y + x + z;
		motor[frontRight] =  -y + x + z;
		motor[backLeft]   =   y - x + z;
		motor[backRight]  =  -y - x + z;
		wait1Msec(20);
	}
}
task controlLiftGrab()
{
	while(1)
	{
		if(vexRT[Btn7U])
		{
			motor[liftGrab]=75;
			wait1Msec(250);
			motor[liftGrab] = 0;
		}
		else if(vexRT[Btn7L])
		{
			motor[liftGrab] = -75;
			wait1Msec(250);
			motor[liftGrab] = 0;
		}
	}
}
task usercontrol()
{
	// User control code here, inside the loop

	startTask(robotDrive);
	startTask(controlLiftGrab);
	while (true)
	{

		// Catapult
		if(vexRT[Btn5U]) // Fire Without Reset
		{
			while(vexRT[Btn5U]);
			fireCatapult();
		}
		else if(vexRT[Btn6U]) // Fire With Reset
		{
			while(vexRT[Btn6U]);
			fireCatapult();
			resetCatapult();
		}
		else if(vexRT[Btn5D]) // Manual Negative
		{
			motor[catapultLeftA]  = -127;
			motor[catapultLeftB]  = -127;
			motor[catapultRightA]  = -127;
			motor[catapultRightB]  = -127;
		}
		else if(vexRT[Btn6D]) // Manual Poisitve
		{
			motor[catapultLeftA]  = 127;
			motor[catapultRightA] = 127;
			motor[catapultLeftB]  = 127;
			motor[catapultRightB] = 127;
		}
		else
		{
			motor[catapultLeftA]  = 0;
			motor[catapultRightA] = 0;
			motor[catapultLeftB]  = 0;
			motor[catapultRightB] = 0;
		}
		
		if(vexRT[Btn8U])
		{
			motor[hookServo] = 80;
		}
		else if(vexRT[Btn8R])
		{
			motor[hookServo] = -30;
		}
		wait1Msec(20);
	}
}
