#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           clawA,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           catapultRightB, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           catapultLeftA, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapultLeftB, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*--------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/
#define SIGN(n) (n<0 ? -1 : 1)
void gyroturn(int deg) // Turn Function using Gyroscope
{
	int gyroticks = deg*10; // Ticks of Gyro
	int P_Factor = 2.5; // P Factor for P Turn
	SensorValue[gyro] = 0; // Reset Gyro Value
	while(abs(SensorValue[gyro]) < abs(gyroticks)) // Wait for Gyro to Finish
	{
		motor[backLeft] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
		motor[backRight] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
		motor[frontLeft] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
		motor[frontRight] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
	}
	motor[backLeft] = -1*SIGN(gyroticks)*15; // Brake Wheels
	motor[backRight] = -1*SIGN(gyroticks)*15;
	motor[frontLeft] = -1*SIGN(gyroticks)*15;
	motor[frontRight] = -1*SIGN(gyroticks)*15;
	wait1Msec(150);
	motor[backLeft] = 0; // Turn Off Wheels
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
int wheeldegs;
void moveForwardsInches(int inches) // Y Axis, Pos=Forward Neg=Backwards
{
	wheeldegs = (inches/12.566)*360; // Calculating Wheel Degrees
	float P_Factor = 0.75; // Factor for P Controller
	nMotorEncoder[backLeft] = 0; // Reset Encoder
	writeDebugStreamLine("%d", wheeldegs);
	while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs)) // Wait for Finish
	{
		motor[backLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[backRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
		motor[frontLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
		motor[frontRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
	}
	motor[backLeft] = -1*SIGN(wheeldegs)*15; // Brake Wheels
	motor[backRight] = -1*SIGN(wheeldegs)*15;
	motor[frontLeft] = -1*SIGN(wheeldegs)*15;
	motor[frontRight] = -1*SIGN(wheeldegs)*15;
	wait1Msec(150);
	motor[backLeft] = 0; // Turn Off Wheels
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}/*
void moveForwardsInches(int inches, int timeout) // Y Axis, Pos=Forward Neg=Backwards
{
time1[T1] = 0;
wheeldegs = (inches/12.566)*360; // Calculating Wheel Degrees
float P_Factor = 0.75; // Factor for P Controller
nMotorEncoder[backLeft] = 0; // Reset Encoder
writeDebugStreamLine("%d", wheeldegs);
while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs) || time1[T1] > timeout) // Wait for Finish
{
motor[backLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
motor[backRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
motor[frontLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
motor[frontRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
}
motor[backLeft] = -1*SIGN(wheeldegs)*15; // Brake Wheels
motor[backRight] = -1*SIGN(wheeldegs)*15;
motor[frontLeft] = -1*SIGN(wheeldegs)*15;
motor[frontRight] = -1*SIGN(wheeldegs)*15;
wait1Msec(150);
motor[backLeft] = 0; // Turn Off Wheels
motor[backRight] = 0;
motor[frontLeft] = 0;
motor[frontRight] = 0;
wait1Msec(150);

}*/
void moveStrafeInches(int inches) // Strafe, Pos=Left Neg=Right
{
	wheeldegs = (inches/12.566)*360;
	float P_Factor = 0.75;
	nMotorEncoder[backLeft] = 0;
	writeDebugStreamLine("%d", wheeldegs);
	while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs))
	{
		motor[backLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[backRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[frontLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
		motor[frontRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
	}
	motor[backLeft] = -1*SIGN(wheeldegs)*15;
	motor[backRight] = -1*SIGN(wheeldegs)*15;
	motor[frontLeft] = -1*SIGN(wheeldegs)*15;
	motor[frontRight] = -1*SIGN(wheeldegs)*15;
	wait1Msec(150);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void clawopen() // Open Claw Function
{
	motor[ClawA] = 127;
	//motor[ClawB] = -127;
	wait1Msec(650);
	motor[ClawA] = 0;
	//motor[ClawB] = 0;
}
void clawclose() // Close Claw Function
{
	motor[ClawA] =-127;
	//motor[ClawB] = 127;
	wait1Msec(650);
	motor[ClawA] = 0;
	//motor[ClawB] = 0;
}
void encoturn(int deg) // Turn based on Encoder Values
{
	float wheeldegs = (deg/90)*706; // Constants found using circle math
	float P_Factor = 0.75; // Factor for P Controller
	nMotorEncoder[backLeft] = 0;
	writeDebugStreamLine("%d", wheeldegs);
	while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs)) // Wait for Encoder to hit value found
	{
		motor[backLeft] = 30+ SIGN(wheeldegs)*127;
		motor[backRight] = 30+ SIGN(wheeldegs)*127;
		motor[frontLeft] = 30+ SIGN(wheeldegs)*127;
		motor[frontRight] = 30+ SIGN(wheeldegs)*127;
	}
	motor[backLeft] = -1*SIGN(wheeldegs)*15; // Brake Wheels
	motor[backRight] = -1*SIGN(wheeldegs)*15;
	motor[frontLeft] = -1*SIGN(wheeldegs)*15;
	motor[frontRight] = -1*SIGN(wheeldegs)*15;
	wait1Msec(150);
	motor[backLeft] = 0; // Stop Wheels
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
void liftup(int degs) // Lift Up using encoders
{
	float goal = (degs/360)*627.2 +  nMotorEncoder[catapultRightB]; // find goal
	int true_goal = (int) goal; // need to cast to int because can't compare int and float
	while(abs(nMotorEncoder[catapultRightB]) < abs(true_goal))
	{
		motor[catapultLeftA]  = 127;
		//motor[catapultRightA] = 127;
		motor[catapultLeftB]  = 127;
		motor[catapultRightB] = 127;
	}
	motor[catapultLeftA]  = 20; // Hold Power
	//motor[catapultRightA] = 20;
	motor[catapultLeftB]  = 20;
	motor[catapultRightB] = 20;
	return;
}
int true_goal_b;
void liftdown(int degs) // Lift Down using encoders (Look at above function for additional comments)
{
	float goal = nMotorEncoder[catapultRightB] - (degs/360)*627.2;
	true_goal_b = (int) goal;
	while(abs(nMotorEncoder[catapultRightB]) > abs(true_goal_b))
	{
		motor[catapultLeftA]  = -127;
		//motor[catapultRightA] = -127;
		motor[catapultLeftB]  = -127;
		motor[catapultRightB] = -127;
	}
	motor[catapultLeftA]  = 15;
	//motor[catapultRightA] = 15;
	motor[catapultLeftB]  = 15;
	motor[catapultRightB] = 15;
	return;
}
int liftgoal = 0;
int liftdone = 1;
task liftPosition // Task to Control Lift Position simultaneously with other subsystems
{
	int oldliftposition = 0; // Start Lift Positio
	while(1)
	{
		if(oldliftposition != liftgoal)
		{
			liftdone = 0;
			if(oldliftposition > liftgoal)
			{
				liftdown(oldliftposition - liftgoal); // If Goal is lower than current, lower lift.
			}
			else
			{
				liftup(liftgoal - oldliftposition);// If Goal is higher than current, raise lift.
			}
			oldliftposition = liftgoal;
			liftdone = 1;
		}
	}
}
int clawgoal = 0;
int clawdone = 1;
task clawPosition // Task to Control Claw Position simultaneously with other subsystems
{
	int oldclawposition = 0;
	while(1)
	{
		if(oldclawposition != clawgoal)
		{
			liftdone = 0;
			if(clawgoal == 0)
			{
				clawclose();
			}
			else if(clawgoal == 1)
			{
				clawopen();
			}
			clawdone = 1;
		}
		wait1Msec(20);
	}
}
//PRESETS
int LIFT_TOP = 928;
int LIFT_FLOOR = 0;
int LIFT_PERIMETER = 0;

int CLAW_OPEN = 1;
int CLAW_CLOSE = 0;

int DISTANCE_START_TO_WALL = 48;
int DISTANCE_THREE_STARS = 54;
int DISTANCE_ONE_TILE = 24;
int DISTANCE_OPEN_CLAW_CLEARANCE = 12;
int DISTANCE_TO_CENTER_CUBE = 35; //32-12-35 right Triangle

int TURN_NINTY = 90;
int TURN_TO_CENTRAL_CUBE = 21; // 32-12-35 right Triangle

void programmingSkills() // Possible Programming Skills, NOT TESTED YET
{
	// Open Claw
	clawclose();
	gyroturn(-TURN_NINTY);
	//3 Stars
	moveForwardsInches(DISTANCE_THREE_STARS);
	clawclose();
	moveForwardsInches(-DISTANCE_THREE_STARS);
	moveStrafeInches(-DISTANCE_ONE_TILE);
	gyroturn(-TURN_NINTY);
	moveForwardsInches(-DISTANCE_ONE_TILE);
	liftup(LIFT_TOP);
	clawopen();
	liftdown(LIFT_TOP);
	// Preloads
	for(int rev = 0; rev < 3; rev++)
	{
		moveForwardsInches(DISTANCE_START_TO_WALL);
		clawclose();
		moveForwardsInches(-DISTANCE_START_TO_WALL);
		liftup(LIFT_TOP);
		clawopen();
		liftdown(LIFT_TOP);
		if(rev != 2)
			moveForwardsInches(DISTANCE_START_TO_WALL);
	}
	// Row of 3 Stars
	gyroturn(TURN_NINTY);
	moveForwardsInches(DISTANCE_THREE_STARS);
	gyroturn(-TURN_NINTY);
	liftup(LIFT_TOP);
	clawopen();
	liftdown(LIFT_TOP);
	// Center Cube
	gyroturn(-TURN_TO_CENTRAL_CUBE);
	clawopen();
	moveForwardsInches(DISTANCE_TO_CENTER_CUBE);
	clawclose();
	moveForwardsInches(-DISTANCE_TO_CENTER_CUBE);
	gyroturn(TURN_TO_CENTRAL_CUBE);
	liftup(LIFT_TOP);
	clawopen();
	liftdown(LIFT_TOP);
	// Tile Cube
	moveForwardsInches(DISTANCE_START_TO_WALL);
	clawclose();
	moveForwardsInches(-DISTANCE_START_TO_WALL);
	liftup(LIFT_TOP);
	clawopen();
}
void auto_left_tile() // Cube Auto for Left Tile
{
	clawclose();
	gyroturn(45); // Place into Position
	moveForwardsInches(51);
	clawclose();
	clawclose(); // Capture Cube
	motor[clawA] = 70;
	//motor[clawB] = 70; // Pinch Claw
	gyroturn(115);
	liftup(300); // Raise Lift to not drag cube on ground
	moveStrafeInches(-42); // Move to side to score cube
	moveForwardsInches(-36);
	liftup(LIFT_TOP); // Lift to Top
	clawopen();
	clawclose(); // Open and Close Claw
	liftdown(LIFT_TOP); // Lower lift
	liftdown(LIFT_TOP); // Lower lift (For some reason needs to be done twise)
}
void auto_right_tile() // Cube Auto for Right Tile -- Same Comments as Above
{
	nMotorEncoder[backLeft] = 0;
	nMotorEncoder[catapultRightB] = 0;
	clawclose();
	gyroturn(-45);
	moveForwardsInches(51);
	clawclose();
	clawclose();
	motor[clawA] = -70;
	//motor[clawB] = 70;
	liftup(450);
	gyroturn(-65);
	moveForwardsInches(-48);
	gyroturn(-55);
	moveForwardsInches(-32);
	liftup(LIFT_TOP-450);
	clawopen();
	clawclose();
	motor[backLeft] =- 80; // Turn Off Wheels
	motor[backRight] = 80;
	motor[frontLeft] = 80;
	motor[frontRight] = -80;
	liftdown(LIFT_TOP);
	liftdown(LIFT_TOP);
	motor[backLeft] = 0; // Turn Off Wheels
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
}
void auto_star_left() // Star Auto for Left Tile
{
	moveForwardsInches(-40); // Move back to descore preload
	moveStrafeInches(-24); // Strafe into position with middle cube
	clawclose(); // Place claw completely outstreached
	liftup(LIFT_TOP-180); // Lift
	moveForwardsInches(-16); // Move Back to knock stars off fence
	clawclose();
	clawopen(); // Use claw to push off
	liftdown(LIFT_TOP);
	liftdown(LIFT_TOP); // Lift down
}
void auto_star_right() // Star Auto for Right Tile -- Same Comments as Above
{
	nMotorEncoder[catapultRightB] = 0;
	moveForwardsInches(-40);
	//	moveStrafeInches(10);
	clawclose();
	liftup(LIFT_TOP-350);
	moveForwardsInches(-35);
	/*
	clawclose();
	clawopen();
	liftdown(LIFT_TOP);
	liftdown(LIFT_TOP);*/
}
task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................
	//auto_right_tile();
	nMotorEncoder[backLeft] = 0;
	nMotorEncoder[catapultRightB] = 0;
	moveForwardsInches(-16);
	clawclose();
	clawclose();
	motor[clawA] = -70;
	moveForwardsInches(-46);
	liftup(950);
	clawopen();
	liftdown(LIFT_TOP);
	liftdown(LIFT_TOP);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
float changeRange(float x, float in_min, float in_max, float out_min, float out_max) // Change Range Function, for squared Drive
{
	return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
task robotDrive()
{
	wait1Msec(5);
	int reverse = 1;
	float slow = 1;
	while(1)
	{
		// Reverse Button
		/*if(vexRT[Btn7D])
		{
		while(vexRT[Btn7D]);
		reverse = -reverse;
		}
		if(vexRT[Btn8D])
		{
		while(Vexrt[Btn8D]);
		slow = slow == 1 ? .5 : 1;
		}*/
		// XDRIVE
		float x,y,z;
		x = changeRange(vexRT[Ch1],-127,127,-1,1);
		x = changeRange(vexRT[Ch1],-127,127,-1,1); // Changing the Range for Squared Inputs
		y = changeRange(vexRT[Ch2],-127,127,-1,1);
		z = changeRange(vexRT[Ch4],-127,127,-1,1);
		x = x*x;
		x = x*x; // Squared Inputs for Better Control
		y = y*y;
		z = z*z;
		x = changeRange(x,-1,1,-127,127) * reverse * slow;
		x = changeRange(x,-1,1,-127,127) * reverse * slow; // Change the Range back and add some multipliers
		y = changeRange(y,-1,1,-127,127) * reverse * slow;
		z = changeRange(z,-1,1,-127,127) * reverse * slow;
		if(vexRT[Ch1] < 0)
			if(vexRT[Ch1] < 0) // Because of Squared Drive, all motor inputs are now positive, so we must fix that
			x = x*-1
		if(vexRT[Ch2] < 0)
			y = y*-1
		if(vexRT[Ch4] < 0)
			z = z*-1
		writeDebugStreamLine("%d %d %d", x, y, z);
		motor[frontLeft]  =  -y + x + z;
		writeDebugStreamLine("%d %d %d", x, y, z); // Debug
		motor[frontLeft]  =  -y + x + z; // Just which way each motor needs to turn to go each direction
		motor[frontRight] =  y + x + z;
		motor[backLeft]   =  y - x + z;
		motor[backRight]  =  -y - x + z;
		wait1Msec(20);
	}
}
task controlLiftGrab()
{
	while(1)
	{
		if(vexRT[Btn5D]) // Close Claw
		{
			motor[ClawA]=127;
			//motor[ClawB]=127;
		}
		else if(vexRT[Btn6D]) // Open Claw
		{
			motor[ClawA]=-127;
			//motor[ClawB]=-127;
		}
		else // No Claw Power
		{
			motor[ClawA]=0;
			//motor[ClawB]=0;
		}
		wait1Msec(25);
	}
}
void usercontrolfunction()
{
	// Drive
	int reverse = 1;
	float slow = 1;
	float x,y,z;
	x = changeRange(vexRT[Ch1],-127,127,-1,1); // Changing the Range for Squared Inputs
	y = changeRange(vexRT[Ch2],-127,127,-1,1);
	z = changeRange(vexRT[Ch4],-127,127,-1,1);
	x = x*x; // Squared Inputs for Better Control
	y = y*y;
	z = z*z;
	x = changeRange(x,-1,1,-127,127) * reverse * slow; // Change the Range back and add some multipliers
	y = changeRange(y,-1,1,-127,127) * reverse * slow;
	z = changeRange(z,-1,1,-127,127) * reverse * slow;
	if(vexRT[Ch1] < 0)
		x = x*-1
	if(vexRT[Ch2] < 0)
		y = y*-1
	if(vexRT[Ch4] < 0)
		z = z*-1
	writeDebugStreamLine("%d %d %d", x, y, z); // Debug
	motor[frontLeft]  =  -y + x + z; // Just which way each motor needs to turn to go each direction
	motor[frontRight] =  y + x + z;
	motor[backLeft]   =  y - x + z;
	motor[backRight]  =  -y - x + z;
	wait1Msec(20);
	// Lift
	if(vexRT[Btn5U]) // Manual Negative
	{
		motor[catapultLeftA]  = -127;
		motor[catapultLeftB]  = -127;
		//motor[catapultRightA]  = -127;
		motor[catapultRightB]  = -127;
	}
	else if(vexRT[Btn6U]) // Manual Posiitve
	{
		motor[catapultLeftA]  = 127;
		//motor[catapultRightA] = 127;
		motor[catapultLeftB]  = 127;
		motor[catapultRightB] = 127;
	}
	else
	{
		motor[catapultLeftA]  = 15;
		//motor[catapultRightA] = 15;
		motor[catapultLeftB]  = 15;
		motor[catapultRightB] = 15;
	}
	// Claw
	if(vexRT[Btn6D]) // Close Claw
	{
		motor[ClawA]=127;
		//motor[ClawB]=127;
	}
	else if(vexRT[Btn5D]) // Open Claw
	{
		motor[ClawA]=-127;
		//motor[ClawB]=-127;
	}
	else // No Claw Power
	{
		motor[ClawA]=0;
		//motor[ClawB]=0;
	}
}
task usercontrol()
{
	// User control code here, inside the loop

	/*startTask(robotDrive);
	startTask(controlLiftGrab);
	while (true)
	{

	// Catapult
	if(vexRT[Btn5U]) // Manual Negative
	{
	motor[catapultLeftA]  = -127;
	motor[catapultLeftB]  = -127;
	motor[catapultRightA]  = -127;
	motor[catapultRightB]  = -127;
	}
	else if(vexRT[Btn6U]) // Manual Poisitve
	{
	motor[catapultLeftA]  = 127;
	motor[catapultRightA] = 127;
	motor[catapultLeftB]  = 127;
	motor[catapultRightB] = 127;
	}
	else
	{
	motor[catapultLeftA]  = 15;
	motor[catapultRightA] = 15;
	motor[catapultLeftB]  = 15;
	motor[catapultRightB] = 15;
	}
	wait1Msec(25);
	}*/ // The Tasks were bugging out causes us to lose control of drive and claw, but not of lift, which is in main task
	while(1)
		usercontrolfunction();

}
