#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           ClawA,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           catapultRightA, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           catapultRightB, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           catapultLeftA, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapultLeftB, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ClawB,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*--------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/
#define SIGN(n) (n<0 ? -1 : 1)
void gyroturn(int deg)
{
	int gyroticks = deg*10;
	int P_Factor = 2.5;
	SensorValue[gyro] = 0;
	while(abs(SensorValue[gyro]) < abs(gyroticks))
	{
		motor[backLeft] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
		motor[backRight] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
		motor[frontLeft] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
		motor[frontRight] = SIGN(gyroticks)*((abs(gyroticks)-abs(SensorValue[gyro]))*P_Factor);
	}
	motor[backLeft] = -1*SIGN(gyroticks)*15;
	motor[backRight] = -1*SIGN(gyroticks)*15;
	motor[frontLeft] = -1*SIGN(gyroticks)*15;
	motor[frontRight] = -1*SIGN(gyroticks)*15;
	wait1Msec(150);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
int wheeldegs;
void moveForwardsInches(int inches)
{
	wheeldegs = (inches/12.566)*360;
	float P_Factor = 0.75;
	nMotorEncoder[backLeft] = 0;
	writeDebugStreamLine("%d", wheeldegs);
	while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs))
	{
		motor[backLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
		motor[backRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[frontLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[frontRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
	}
	motor[backLeft] = -1*SIGN(wheeldegs)*15;
	motor[backRight] = -1*SIGN(wheeldegs)*15;
	motor[frontLeft] = -1*SIGN(wheeldegs)*15;
	motor[frontRight] = -1*SIGN(wheeldegs)*15;
	wait1Msec(150);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
void moveStrafeInches(int inches)
{
	wheeldegs = (inches/12.566)*360;
	float P_Factor = 0.75;
	nMotorEncoder[backLeft] = 0;
	writeDebugStreamLine("%d", wheeldegs);
	while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs))
	{
		motor[backLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[backRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor)*-1)*SIGN(wheeldegs);
		motor[frontLeft] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
		motor[frontRight] = (30+ ((abs(nMotorEncoder[backLeft])-abs(wheeldegs))*P_Factor))*SIGN(wheeldegs);
	}
	motor[backLeft] = -1*SIGN(wheeldegs)*15;
	motor[backRight] = -1*SIGN(wheeldegs)*15;
	motor[frontLeft] = -1*SIGN(wheeldegs)*15;
	motor[frontRight] = -1*SIGN(wheeldegs)*15;
	wait1Msec(150);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void clawopen()
{
	motor[ClawA] = -127;
	motor[ClawB] = -127;
	wait1Msec(650);
	motor[ClawA] = 0;
	motor[ClawB] = 0;
}
void clawclose()
{
	motor[ClawA] =127;
	motor[ClawB] = 127;
	wait1Msec(650);
	motor[ClawA] = 0;
	motor[ClawB] = 0;
}
void encoturn(int deg)
{
	clawclose();
	float wheeldegs = (deg/90)*706;
	float P_Factor = 0.75;
	nMotorEncoder[backLeft] = 0;
	writeDebugStreamLine("%d", wheeldegs);
	while(abs(nMotorEncoder[backLeft]) < abs(wheeldegs))
	{
		motor[backLeft] = 30+ SIGN(wheeldegs)*127;
		motor[backRight] = 30+ SIGN(wheeldegs)*127;
		motor[frontLeft] = 30+ SIGN(wheeldegs)*127;
		motor[frontRight] = 30+ SIGN(wheeldegs)*127;
	}
	motor[backLeft] = -1*SIGN(wheeldegs)*15;
	motor[backRight] = -1*SIGN(wheeldegs)*15;
	motor[frontLeft] = -1*SIGN(wheeldegs)*15;
	motor[frontRight] = -1*SIGN(wheeldegs)*15;
	wait1Msec(150);
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
	wait1Msec(150);

}
void liftup(int degs)
{
	float goal = (degs/360)*627.2 +  nMotorEncoder[catapultRightB];
	int true_goal = (int) goal;
	while(nMotorEncoder[catapultRightB] < true_goal)
	{
			motor[catapultLeftA]  = 127;
			motor[catapultRightA] = 127;
			motor[catapultLeftB]  = 127;
			motor[catapultRightB] = 127;
	}
	motor[catapultLeftA]  = 15;
	motor[catapultRightA] = 15;
	motor[catapultLeftB]  = 15;
	motor[catapultRightB] = 15;
	return;
}
void liftdown(int degs)
{
	float goal = nMotorEncoder[catapultRightB] - (degs/360)*627.2;
	int true_goal = (int) goal;
	while(nMotorEncoder[catapultRightB] > true_goal)
	{
			motor[catapultLeftA]  = 127;
			motor[catapultRightA] = 127;
			motor[catapultLeftB]  = 127;
			motor[catapultRightB] = 127;
	}
	motor[catapultLeftA]  = 15;
	motor[catapultRightA] = 15;
	motor[catapultLeftB]  = 15;
	motor[catapultRightB] = 15;
	return;
}
int liftgoal = 0;
int liftdone = 1;
task liftPosition
{
	int oldliftposition = 0;
	while(1)
	{
		if(oldliftposition != liftgoal)
		{
			liftdone = 0;
			if(oldliftposition > liftgoal)
			{
				liftdown(oldliftposition - liftgoal);
			}
			else
			{
				liftup(liftgoal - oldliftposition);
			}
			oldliftposition = nMotorEncoder[catapultRightB];
			liftdone = 1;
		}
	}
}
int clawgoal = 0;
int clawdone = 1;
task clawPosition
{
	int oldclawposition = 0;
	while(1)
	{
		if(oldclawposition != clawgoal)
		{
			liftdone = 0;
			if(clawgoal == 0)
			{
				clawclose();
			}
			else if(clawgoal == 1)
			{
				clawopen();
			}
			clawdone = 1;
		}
		wait1Msec(20);
	}
}
//PRESETS
int LIFT_TOP = 0;
int LIFT_FLOOR = 0;
int LIFT_PERIMETER = 0;

int CLAW_OPEN = 1;
int CLAW_CLOSE = 0;

int DISTANCE_START_TO_WALL = 48;
int DISTANCE_THREE_STARS = 54;
int DISTANCE_ONE_TILE = 24;
int DISTANCE_OPEN_CLAW_CLEARANCE = 12;
int DISTANCE_TO_CENTER_CUBE = 35; //32-12-35 right Triangle

int TURN_NINTY = 90;
int TURN_TO_CENTRAL_CUBE = 21; // 32-12-35 right Triangle

void programmingSkills()
{
	// Open Claw
	moveStrafeInches(-DISTANCE_OPEN_CLAW_CLEARANCE);
	clawclose();
	moveStrafeInches(DISTANCE_OPEN_CLAW_CLEARANCE);
	//3 Stars
	moveForwardsInches(DISTANCE_THREE_STARS);
	clawclose();
	moveForwardsInches(-DISTANCE_THREE_STARS);
	moveStrafeInches(-DISTANCE_ONE_TILE);
	gyroturn(TURN_NINTY);
	moveForwardsInches(-DISTANCE_ONE_TILE);
	liftup(LIFT_TOP);
	clawopen();
	liftdown(LIFT_TOP);
	// Preloads
	for(int rev = 0; rev < 3; rev++)
	{
		moveForwardsInches(DISTANCE_START_TO_WALL);
		clawclose();
		moveForwardsInches(-DISTANCE_START_TO_WALL);
		liftup(LIFT_TOP);
		clawopen();
		liftdown(LIFT_TOP);
		if(rev != 2)
			moveForwardsInches(DISTANCE_START_TO_WALL);
	}
	// Row of 3 Stars
	gyroturn(-TURN_NINTY);
	moveForwardsInches(DISTANCE_THREE_STARS);
	gyroturn(TURN_NINTY);
	liftup(LIFT_TOP);
	clawopen();
	liftdown(LIFT_TOP);
	// Center Cube
	gyroturn(TURN_TO_CENTRAL_CUBE);
	clawopen();
	moveForwardsInches(DISTANCE_TO_CENTER_CUBE);
	clawclose();
	moveForwardsInches(-DISTANCE_TO_CENTER_CUBE);
	gyroturn(-TURN_TO_CENTRAL_CUBE);
	liftup(LIFT_TOP);
	clawopen();
	liftdown(LIFT_TOP);
	// Tile Cube
	moveForwardsInches(DISTANCE_START_TO_WALL);
	clawclose();
	moveForwardsInches(-DISTANCE_START_TO_WALL);
	liftup(LIFT_TOP);
	clawopen();
}
void auto_left_tile()
{
	clawclose();
	moveForwardsInches(51)
	gyroturn(135);
	moveForwardsInches(-18);
	liftup(LIFT_TOP);
	clawopen();
}
void auto_right_tile()
{
	clawclose();
	moveForwardsInches(51)
	gyroturn(-135);
	moveForwardsInches(-18);
	liftup(LIFT_TOP);
	clawopen();
}
task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................
	auto_left_tile();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
float changeRange(float x, float in_min, float in_max, float out_min, float out_max)
{
	return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
task robotDrive()
{
	wait1Msec(5);
	int reverse = 1;
	float slow = 1;
	while(1)
	{
		// Reverse Button
		/*if(vexRT[Btn7D])
		{
		while(vexRT[Btn7D]);
		reverse = -reverse;
		}
		if(vexRT[Btn8D])
		{
		while(Vexrt[Btn8D]);
		slow = slow == 1 ? .5 : 1;
		}*/
		// XDRIVE
		float x,y,z;
		x = changeRange(vexRT[Ch1],-127,127,-1,1);
		y = changeRange(vexRT[Ch2],-127,127,-1,1);
		z = changeRange(vexRT[Ch4],-127,127,-1,1);
		x = x*x;
		y = y*y;
		z = z*z;
		x = changeRange(x,-1,1,-127,127) * reverse * slow;
		y = changeRange(y,-1,1,-127,127) * reverse * slow;
		z = changeRange(z,-1,1,-127,127) * reverse * slow;
		if(vexRT[Ch1] < 0)
			x = x*-1
		if(vexRT[Ch2] < 0)
			y = y*-1
		if(vexRT[Ch4] < 0)
			z = z*-1
		writeDebugStreamLine("%d %d %d", x, y, z);
		motor[frontLeft]  =  -y + x + z;
		motor[frontRight] =  y + x + z;
		motor[backLeft]   =  y - x + z;
		motor[backRight]  =  -y - x + z;
		wait1Msec(20);
	}
}
task controlLiftGrab()
{
	while(1)
	{
		if(vexRT[Btn5D])
		{
			motor[ClawA]=127;
			motor[ClawB]=127;
		}
		else if(vexRT[Btn6D])
		{
			motor[ClawA]=-127;
			motor[ClawB]=-127;
		}
		else
		{
			motor[ClawA]=0;
			motor[ClawB]=0;
		}
	}
}
task usercontrol()
{
	// User control code here, inside the loop

	startTask(robotDrive);
	startTask(controlLiftGrab);
	while (true)
	{

		// Catapult
		if(vexRT[Btn5U]) // Manual Negative
		{
			motor[catapultLeftA]  = -127;
			motor[catapultLeftB]  = -127;
			motor[catapultRightA]  = -127;
			motor[catapultRightB]  = -127;
		}
		else if(vexRT[Btn6U]) // Manual Poisitve
		{
			motor[catapultLeftA]  = 127;
			motor[catapultRightA] = 127;
			motor[catapultLeftB]  = 127;
			motor[catapultRightB] = 127;
		}
		else
		{
			motor[catapultLeftA]  = 15;
			motor[catapultRightA] = 15;
			motor[catapultLeftB]  = 15;
			motor[catapultRightB] = 15;
		}
	}
}
